// <auto-generated />
using System;
using KCrm.Core.Entity;
using KCrm.Data.Projects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KCrm.Data.__Migrations.Projects
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("project")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("KCrm.Core.Entity.Projects.ProjectActivityEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<EventPayload>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_activities");

                    b.HasIndex("EventName")
                        .HasDatabaseName("ix_project_activities_event_name");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_activities_project_id");

                    b.ToTable("project_activities");
                });

            modelBuilder.Entity("KCrm.Core.Entity.Projects.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(8096)
                        .IsUnicode(true)
                        .HasColumnType("character varying(8096)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDateTimeUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date_time_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PlanedEndDateTimeUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("planed_end_date_time_utc");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("project_type");

                    b.Property<DateTime?>("StartDateTimeUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date_time_utc");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_name");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("KCrm.Core.Entity.Projects.ProjectHasTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_project_has_tags");

                    b.HasIndex("TagId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_has_tags_tag_id_project_id");

                    b.ToTable("project_has_tags");
                });

            modelBuilder.Entity("KCrm.Core.Entity.Projects.ProjectHasUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserRoleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_role_type");

                    b.HasKey("Id")
                        .HasName("pk_project_has_users");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_has_users_project_id_user_id");

                    b.ToTable("project_has_users");
                });
#pragma warning restore 612, 618
        }
    }
}
