replicaCount: 1

imagePullSecrets:
  - name: regcred

fullnameOverride: crm-front
frontNginxConfigMapName: "front-nginx-conf"

ingress:
  enabled: true
  hosts:
    - host: crm.local.lab.pl
      paths:
        - path: /
          pathType: ImplementationSpecific