version: "3.7"
services: 
    postgres:        
        image: postgres:11.8        
        ports:
            - "${DB_PORT:-15432}:5432"
        volumes:
            - pg.data:/var/lib/postgresql/data        
        environment:            
            POSTGRES_USER: crm
            POSTGRES_PASSWORD: crm.7777
    webadmin:
        image: dpage/pgadmin4:5.0
        ports:
            - "${ADMIN_PORT:-9999}:80"
        environment:         
            PGADMIN_DEFAULT_EMAIL: admin@mail.fake
            PGADMIN_DEFAULT_PASSWORD: admin#7777

    files:
        image: minio/minio:RELEASE.2021-03-26T00-00-41Z
        ports: 
            -  ${MINIO_PORT:-9000}:9000
        volumes:
            - files.data:/storage    
        command:  server /storage
        environment:
            MINIO_ROOT_USER: "crmfiles"
            MINIO_ROOT_PASSWORD: "crmfiles#7777"
            #MINIO_REGION: "eu-west-1"            
volumes: 
    pg.data:            
    files.data: