version: "3.7"
services: 
    postgres:        
        image: postgres:11.8        
        ports:
            - "${DB_PORT:-15432}:5432"
        volumes:
            - pg.data:/var/lib/postgresql/data        
        environment:            
            POSTGRES_USER: crm
            POSTGRES_PASSWORD: crm.7777
    webadmin:
        image: dpage/pgadmin4:5.0
        ports:
            - "${ADMIN_PORT:-9999}:80"
        environment:         
            PGADMIN_DEFAULT_EMAIL: admin@mail.fake
            PGADMIN_DEFAULT_PASSWORD: admin123
volumes: 
    pg.data:            